---
server:
  port: 8081
#dubbo配置
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
    id: my-registry
  protocol:
    port: 20882
    name: dubbo
    id: dubbo
  application:
    name: consumer
  provider:
    timeout: 5000
  scan:
    basePackages: com.demo.service
#日志
logging:
  level:
    org:
      springframework: INFO
